repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
      args: ['--config=setup.cfg',  '--exclude=./cla_frontend/settings/*']
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.5.0
    hooks:
      - id: pip-compile
        language_version: python2.7
        name: pip-compile docs.in
        files: (base|docs).in
        args: [requirements/source/docs.in, "--output-file", requirements/generated/docs.txt]
      - id: pip-compile
        language_version: python2.7
        name: pip-compile dev.in
        files: (base|dev).in
        args: [requirements/source/dev.in, "--output-file", requirements/generated/dev.txt]
      - id: pip-compile
        language_version: python2.7
        name: pip-compile lint.in
        files: (base|lint).in
        args: [requirements/source/lint.in, "--output-file", requirements/generated/lint.txt]
      - id: pip-compile
        language_version: python2.7
        name: pip-compile testing.in
        files: (base|testing).in
        args: [requirements/source/testing.in, "--output-file", requirements/generated/testing.txt]
      - id: pip-compile
        language_version: python2.7
        name: pip-compile production.in
        files: (base|production).in
        args: [requirements/source/production.in, "--output-file", requirements/generated/production.txt]