# NB: this is only used for *local development*
# see Dockerfile for deployed version
version: "3.9"
services:
  start_applications:
    image: jwilder/dockerize
    security_opt:
      - no-new-privileges:true
    command: >
      -wait tcp://cla_frontend:8000
      -wait tcp://cla_socketserver:8005
      -wait tcp://cla_backend:8000
      -wait-retry-interval 10s
      -timeout 180s
    depends_on:
      - cla_frontend

  cla_frontend:
    build:
      context: .
      target: ${ENVIRONMENT:-development}
    stdin_open: true
    tty: true
    volumes:
      - .:/home/app
    ports:
      - "8011:8000"
    container_name:
      cla_frontend
    depends_on:
      - cla_backend
      - cla_socketserver
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://clabackend:8000
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CLA_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f
      SOCKETIO_SERVER_URL: http://clasocketserver:8005/socket.io
      SOCKETIO_SERVICE_URL: clasocketserver:8005/socket.io/
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-CHANGE_ME}
      GA_ID: ${GA_ID:-CHANGE_ME}
      GA_DOMAIN: ${GA_DOMAIN:-localhost}
      SITE_HOSTNAME: clasocketserver
      STATIC_FILES_BACKEND: local
      ALLOWED_HOSTS: "*"
      SESSION_COOKIE_SECURE: "False"

  cla_socketserver:
    image: ${CLA_SOCKET_SERVER_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/cla_frontend_socket_server:master}
    container_name:
      cla_socket_server
    environment:
      SITE_HOSTNAME: clasocketserver

  db:
    image: postgres:11.6-alpine
    ports:
      - '5432'
    security_opt:
      - no-new-privileges:true
    container_name:
      cla_frontend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend

  cla_backend:
    build:
      context: .
      target: ${ENVIRONMENT:-development}
    ports:
      - '8010:8000'
    stdin_open: true
    tty: true
#    volumes:
#      - .:/home/app
    depends_on:
      - db
    container_name:
      cla_backend
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      DB_NAME: cla_backend
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      BACKEND_ENABLED: "True"
      LOAD_SEED_DATA: "True"
      LOAD_TEST_DATA: "True"
      LOAD_END_TO_END_FIXTURES: "True"
      ADMIN_USER: cla_admin
      STATIC_FILES_BACKEND: local
      ADMIN_PASSWORD: cla_admin
      ALLOWED_HOSTS: "*"

