version: '3.9'

services:
  cla_frontend:
    build: .
    ports:
      - "8000:8000"
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://clabackend:8000
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CALL_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f
      SOCKETIO_SERVER_URL: /socket.io

  db:
    image: postgres:11.6-alpine
    ports:
      - ${DOCKER_DATABASE_PORT_MAPPING:-5433:5432}
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend

  cla_backend: &cla_backend
    build:
      context: https://github.com/ministryofjustice/cla_backend.git#master
      target: ${ENVIRONMENT:-development}
    ports:
      - '8010:8000'
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment: &cla_backend_environment
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      DB_NAME: cla_backend
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      BACKEND_ENABLED: "True"
      LOAD_SEED_DATA: "True"
      LOAD_TEST_DATA: "True"
      LOAD_END_TO_END_FIXTURES: "True"
      ADMIN_USER: cla_admin
      STATIC_FILES_BACKEND: local
      ADMIN_PASSWORD: cla_admin
      ALLOWED_HOSTS: "*"
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS:-cla_backend.settings.base}
      CELERY_BROKER_URL: "amqp://rabbitmq"
      PREVIOUS_DIVERSITY_PRIVATE_KEY: ${PREVIOUS_DIVERSITY_PRIVATE_KEY:-}
      EMAIL_ORCHESTRATOR_URL: ${EMAIL_ORCHESTRATOR_URL:-}