version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  node: circleci/node@5.0.2
  cla-end-to-end-tests: ministryofjustice/cla-end-to-end-tests@volatile
  aws-cli: circleci/aws-cli@4.1 # use v4 of this orb
  aws-ecr: circleci/aws-ecr@9.0 # this orb doesn't support OIDC v2, so we use aws-cli to authenticate

# ------------------
# EXECUTORS
# these are ones we use rather than one from rom the orb
# ------------------

executors:
  cloud-platform-executor:
    docker:
      - image: ministryofjustice/cloud-platform-tools:2.1
  python2-executor:
    docker:
      - image: cimg/python:2.7
  python3-executor:
    docker:
      - image: cimg/python:3.7

# ------------------
#
# REFERENCES
#
# ------------------

references:
  install_helm: &install_helm
    run:
      name: Install helm v3
      command: |
        wget https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz
        tar -zxvf helm-v3.2.4-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm

# ------------------
#
# JOBS
#
# ------------------
jobs:
  pip-compile:
    executor: python2-executor
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            echo "Installing ibcurl4-gnutls-dev because it is required for pycurl"
            sudo apt-get update
            sudo apt-get install -y libcurl4-gnutls-dev
            pip install virtualenv
            virtualenv pip-compile-env
      - restore_cache:
          keys:
            - pip-v1-pip-compile
      - run:
          name: Install dependencies
          command: |
            source pip-compile-env/bin/activate
            pip install pre-commit==1.14.2
      - save_cache:
          key: pip-v1-pip-compile
          paths:
            - "~/.cache/pip"
      - run:
          name: Check for changes with pip-compile
          command: |
            source pip-compile-env/bin/activate
            pre-commit run pip-compile --files requirements-dev.in
            pre-commit run pip-compile --files requirements-docs.in
            pre-commit run pip-compile --files requirements-testing.in
            pre-commit run pip-compile --files requirements-production.in
  python_unit_test:
    docker:
      - image: cimg/python:2.7
        environment:
          DJANGO_SETTINGS_MODULE: cla_frontend.settings.testing
          SECRET_KEY: testing_key
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install pip==18.1
      - restore_cache:
          keys:
            - pip-v1-{{ checksum "requirements/generated/requirements-base.txt" }}-{{ checksum "requirements/generated/requirements-testing.txt" }}
      - run:
          name: Install dependencies
          command: |
            source env/bin/activate
            pip install --requirement requirements/generated/requirements-testing.txt
      - save_cache:
          key: pip-v1-{{ checksum "requirements/generated/requirements-base.txt" }}-{{ checksum "requirements/generated/requirements-testing.txt" }}
          paths:
            - "~/.cache/pip"
      - run:
          name: Run unit tests
          command: |
            source env/bin/activate
            python manage.py test --verbosity=2
  socket_server_tests:
    docker:
      - image: cimg/node:18.8.0

    steps:
      - checkout
      - node/install:
          node-version: "18"
      - run:
          working_directory: ./cla_socketserver
          name: Install dependencies
          command: |
            npm install --include dev
      - run:
          working_directory: ./cla_socketserver
          name: Run tests
          command: |
            npm run test
  javascript_unit_test:
    docker:
      - image: cimg/node:18.8.0
        environment:
          DJANGO_SETTINGS_MODULE: cla_frontend.settings.test
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "8.9.3"
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node JS dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y libfontconfig
            ./npm_git_wrapper.sh
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - "./node_modules"
      - restore_cache:
          keys:
            - bower-v1-{{ checksum "bower.json" }}
      - run:
          name: Install Bower dependencies
          command: npm run bower
      - save_cache:
          key: bower-v1-{{ checksum "bower.json" }}
          paths:
            - "./cla_frontend/assets-src/vendor"
      - run:
          name: Bundle JavaScript
          command: npm run js
      - run:
          name: Run Jasmine unit tests
          command: |
            npm install
            npm run test-single-run

# ------------------
#
# WORKFLOWS
#
# ------------------
  behave:
    executor: aws-ecr/default
    environment:
      SESSION_COOKIE_NAME: "SID"
      SESSION_COOKIE_SECURE: "False"
      SESSION_COOKIE_HTTPONLY: "False"
      SESSION_COOKIE_SAMESITE: "None"
      DISABLE_SAMESITE_MIDDLEWARE: "True"
      SECURE_CONTENT_TYPE_NOSNIFF: "False"
      CSRF_COOKIE_SECURE: "False"
    steps:
      - checkout:
          path: cla_frontend
      - run: |
          cd cla_frontend
          source .circleci/define_build_environment_variables
          export APP_IMAGE=$ECR_URL_APP:$IMAGE_TAG
          export SOCKET_IMAGE=$ECR_URL_SOCKET_SERVER:$IMAGE_TAG
          echo "export CLA_FRONTEND_IMAGE=$APP_IMAGE; export CLA_SOCKET_SERVER_IMAGE=$SOCKET_IMAGE" >> $BASH_ENV
          echo "Setting CLA Frontend image $APP_IMAGE"
          echo "Setting CLA Socket Server image $SOCKET_IMAGE"
      - cla-end-to-end-tests/behave

workflows:
  version: 2
  test_and_build:
    jobs:
      - pip-compile
      - python_unit_test
      - socket_server_tests
      - javascript_unit_test
      - behave:
          requires:
            - python_unit_test
            - javascript_unit_test
            - socket_server_tests
          context:
            - laa-cla-frontend

