#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
built_tag="$1"
repository="$2"

case $repository in
  app)
      docker_repository="${ECR_URL_APP}"
      push_metrics="yes"
      ;;
  socket-server)
      docker_repository="${ECR_URL_SOCKET_SERVER}"
      push_metrics="no"
      ;;
esac

export CLEANED_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
function tag_and_push() {
  tag="$1"
  echo
  echo "Tagging and pushing $tag..."
  docker tag $built_tag $tag
  docker push $tag
}

tag_and_push "$docker_repository:$safe_git_branch.$short_sha"
tag_and_push "$docker_repository:$safe_git_branch"

if [ "$CIRCLE_BRANCH" == "master" ]; then
  tag_and_push "$docker_repository:latest"
fi
if [ "$push_metrics" == "yes" ]; then
  metric_built_tag="$repository:metrics.$CIRCLE_SHA1"
  metric_push_tag="$docker_repository:$METRICS_IMAGE_TAG"
  echo "Tagging and pushing $metric_built_tag."
  docker tag $metric_built_tag $metric_push_tag
  docker push $metric_push_tag
fi
