# Default values for cla-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cla_frontend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

host: 'localhost'

ingress:
  enabled: true
  annotations: {}
  whitelist:
    # MoJ
    - 81.134.202.29/32
    # MoJ/LAA
    - 52.17.239.55/32
    - 62.25.109.201/32
    - 62.25.109.203/32
    # ATOS datacentre
    - 157.203.176.0/24
    - 157.203.177.0/24
    # LAA Manchester/32
    - 62.25.109.201/32
    - 62.25.109.203/32
    - 31.97.19.127/32
    - 31.67.24.68/32
    # ARK Data Center IP ranges.
    - 194.33.192.0/25
    - 194.33.196.0/25
    # Kubernetes - live0
    - 34.247.134.240/32
    - 34.251.93.81/32
    - 52.17.133.167/32
    # Kubernetes - live1
    - 35.178.209.113/32
    - 3.8.51.207/32
    - 35.177.252.54/32
    - 3.11.49.71/32
    - 18.130.126.34/32
    - 18.134.21.79/32
    # HGS, new Civil Legal Aid call centre provider from Autumn 2019
    - 213.78.108.84/32
    - 84.43.86.100/32
    - 185.38.246.208/32
    - 185.91.131.4/32
    # CHS
    - 52.210.114.89/32

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
