# Default values for cla-frontend in a production environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
environment: "prod"

secretName: ~ # TODO: Remove this line as part of live switch-over as we are not using a custom production domain yet
ingress:
  whitelist: []

envVars:
  BACKEND_BASE_URI:
    value: "https://fox.civillegaladvice.service.gov.uk"
  GA_ID:
    value: UA-37377084-19
  GA_DOMAIN:
    value: service.gov.uk
