# Default values for cla-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image:
  repository: cla_frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

socketServer:
  image:
    repository: cla_frontend_socket_server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

host: 'localhost'

ingress:
  enabled: true
  annotations: {}
  whitelist:
    # MoJ
    - 81.134.202.29/32
    # MoJ/LAA
    - 52.17.239.55/32
    - 62.25.109.201/32
    - 62.25.109.203/32
    # ATOS datacentre
    - 157.203.176.0/24
    - 157.203.177.0/24
    # LAA Manchester/32
    - 62.25.109.201/32
    - 62.25.109.203/32
    - 31.97.19.127/32
    - 31.67.24.68/32
    # ARK Data Center IP ranges.
    - 194.33.192.0/25
    - 194.33.196.0/25
    # Kubernetes - live0
    - 34.247.134.240/32
    - 34.251.93.81/32
    - 52.17.133.167/32
    # Kubernetes - live1
    - 35.178.209.113/32
    - 3.8.51.207/32
    - 35.177.252.54/32
    - 3.11.49.71/32
    - 18.130.126.34/32
    - 18.134.21.79/32
    # HGS, new Civil Legal Aid call centre provider from Autumn 2019
    - 213.78.108.84/32
    - 84.43.86.100/32
    - 185.38.246.208/32
    - 185.91.131.4/32
    # CHS
    - 52.210.114.89/32

envVars:
  STATIC_FILES_BACKEND:
    value: s3
  AWS_STATIC_FILES_STORAGE_BUCKET_NAME:
    secret:
      name: s3
      key: static_files_bucket_name
  AWS_ACCESS_KEY_ID:
    secret:
      name: s3
      key: access_key_id
  AWS_SECRET_ACCESS_KEY:
    secret:
      name: s3
      key: secret_access_key
  AWS_S3_REGION_NAME:
    value: "eu-west-2"
  AWS_S3_HOST:
    value: "s3.eu-west-2.amazonaws.com"
  S3_USE_SIGV4:
    value: "True"
  SECRET_KEY:
    secret:
      name: secret
      key: value
  DEBUG:
    value: "False"
  SOCKETIO_SERVER_URL:
    value: "/socket.io"
  CALL_CENTRE_CLIENT_ID:
    secret:
      name: call-centre
      key: client_id
  CALL_CENTRE_SECRET_ID:
    secret:
      name: call-centre
      key: secret_id
  CLA_PROVIDER_CLIENT_ID:
    secret:
      name: cla-provider
      key: client_id
  CLA_PROVIDER_SECRET_ID:  # This is a key change from TD, so make sure settings/base.py uses the right name
    secret:
      name: cla-provider
      key: secret_id
  OS_PLACES_API_KEY:
    secret:
      name: os-places
      key: api_key
  SENTRY_PUBLIC_DSN:
    secret:
      name: sentry
      key: dsn
  ZENDESK_API_TOKEN:
    secret:
      name: zendesk-api
      key: token
  ZENDESK_API_USERNAME:
    secret:
      name: zendesk-api
      key: username
