# Default values for cla-frontend in a training environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "training"

ingress:
  whitelist: []

envVars:
  BACKEND_BASE_URI:
    # Using service name instead of external domain name
    value: "http://cla-backend-app.laa-cla-backend-training.svc.cluster.local"
  GA_ID:
    value: UA-37377084-20
  GA_DOMAIN:
    value: cloud-platform.service.justice.gov.uk
