# Default values for cla-frontend in a production environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4
environment: "prod"


# Disable whitelist for production
ingress:
  whitelist: []

envVars:
  BACKEND_BASE_URI:
    # Using service name instead of external domain name
    value: "http://cla-backend-app.laa-cla-backend-production.svc.cluster.local"
