#!/bin/sh -e

source .circleci/define_build_environment_variables
built_tag="$1"

function tag_and_push() {
  tag="$1"
  echo
  echo "Tagging and pushing $tag..."
  docker tag $built_tag $tag
  docker push $tag
}

if [ "$CIRCLE_BRANCH" == "master" ]; then
  tag_and_push "$ECR_DOCKER_REGISTRY/$ECR_DOCKER_IMAGE:$CIRCLE_SHA1"
  tag_and_push "$DOCKER_HUB_REGISTRY/$DOCKER_HUB_IMAGE:$CIRCLE_SHA1"
  tag_and_push "$DOCKER_HUB_REGISTRY/$DOCKER_HUB_IMAGE:$safe_git_branch.$short_sha"
fi
tag_and_push "$ECR_DOCKER_REGISTRY/$ECR_DOCKER_IMAGE:$safe_git_branch"
tag_and_push "$ECR_DEPLOY_IMAGE"
tag_and_push "$DOCKER_HUB_REGISTRY/$DOCKER_HUB_IMAGE:$safe_git_branch.latest"
