(function(){
  'use strict';

  angular.module('cla.controllers.operator')
    .controller('CallbacksCtrl',
      ['$scope',
        function($scope) {
          $scope.callbackData = [
            {day: 1, hour: 1, value: 5},
            {day: 1, hour: 2, value: 0},
            {day: 1, hour: 3, value: 0},
            {day: 1, hour: 4, value: 0},
            {day: 1, hour: 5, value: 0},
            {day: 1, hour: 6, value: 0},
            {day: 1, hour: 7, value: 2},
            {day: 1, hour: 8, value: 4},
            {day: 1, hour: 9, value: 0},
            {day: 1, hour: 10, value: 0},
            {day: 1, hour: 11, value: 0},
            {day: 1, hour: 12, value: 0},
            {day: 2, hour: 1, value: 0},
            {day: 2, hour: 2, value: 0},
            {day: 2, hour: 3, value: 1},
            {day: 2, hour: 4, value: 0},
            {day: 2, hour: 5, value: 0},
            {day: 2, hour: 6, value: 5},
            {day: 2, hour: 7, value: 0},
            {day: 2, hour: 8, value: 0},
            {day: 2, hour: 9, value: 0},
            {day: 2, hour: 10, value: 0},
            {day: 2, hour: 11, value: 0},
            {day: 2, hour: 12, value: 0},
            {day: 3, hour: 1, value: 0},
            {day: 3, hour: 2, value: 0},
            {day: 3, hour: 3, value: 0},
            {day: 3, hour: 4, value: 0},
            {day: 3, hour: 5, value: 0},
            {day: 3, hour: 6, value: 0},
            {day: 3, hour: 7, value: 0},
            {day: 3, hour: 8, value: 0},
            {day: 3, hour: 9, value: 1},
            {day: 3, hour: 10, value: 0},
            {day: 3, hour: 11, value: 0},
            {day: 3, hour: 12, value: 0},
            {day: 4, hour: 1, value: 0},
            {day: 4, hour: 2, value: 0},
            {day: 4, hour: 3, value: 0},
            {day: 4, hour: 4, value: 0},
            {day: 4, hour: 5, value: 0},
            {day: 4, hour: 6, value: 0},
            {day: 4, hour: 7, value: 7},
            {day: 4, hour: 8, value: 3},
            {day: 4, hour: 9, value: 0},
            {day: 4, hour: 10, value: 0},
            {day: 4, hour: 11, value: 0},
            {day: 4, hour: 12, value: 0},
            {day: 4, hour: 1, value: 0},
            {day: 4, hour: 2, value: 0},
            {day: 4, hour: 3, value: 4},
            {day: 4, hour: 4, value: 0},
            {day: 4, hour: 5, value: 0},
            {day: 4, hour: 6, value: 0},
            {day: 4, hour: 7, value: 0},
            {day: 4, hour: 8, value: 0},
            {day: 4, hour: 9, value: 0},
            {day: 4, hour: 10, value: 0},
            {day: 4, hour: 11, value: 0},
            {day: 4, hour: 12, value: 0},
            {day: 5, hour: 1, value: 0},
            {day: 5, hour: 2, value: 0},
            {day: 5, hour: 3, value: 0},
            {day: 5, hour: 4, value: 0},
            {day: 5, hour: 5, value: 6},
            {day: 5, hour: 6, value: 0},
            {day: 5, hour: 7, value: 0},
            {day: 5, hour: 8, value: 0},
            {day: 5, hour: 9, value: 10},
            {day: 5, hour: 10, value: 0},
            {day: 5, hour: 11, value: 0},
            {day: 5, hour: 12, value: 15},
            {day: 6, hour: 1, value: 0},
            {day: 6, hour: 2, value: 1},
            {day: 6, hour: 3, value: 0},
            {day: 6, hour: 4, value: 0},
            {day: 6, hour: 5, value: 1},
            {day: 6, hour: 6, value: 1},
            {day: 6, hour: 7, value: 0},
            {day: 6, hour: 8, value: 4},
            {day: 6, hour: 9, value: 0},
            {day: 6, hour: 10, value: 0},
            {day: 6, hour: 11, value: 7},
            {day: 6, hour: 12, value: 0},
            {day: 7, hour: 1, value: 0},
            {day: 7, hour: 2, value: 0},
            {day: 7, hour: 3, value: 0},
            {day: 7, hour: 4, value: 0},
            {day: 7, hour: 5, value: 0},
            {day: 7, hour: 6, value: 0},
            {day: 7, hour: 7, value: 0},
            {day: 7, hour: 8, value: 0},
            {day: 7, hour: 9, value: 0},
            {day: 7, hour: 10, value: 0},
            {day: 7, hour: 11, value: 0},
            {day: 7, hour: 12, value: 0}
          ];
        }
      ]
    );
})();
