{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cla-frontend.fullname" . -}}
{{- $ingressName := printf "%s-%s" $fullName "v122" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "cla-frontend.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $ingressName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- end }}
    {{- if .Values.ingress.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "cla-frontend.whitelist" . }}"
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippets: |
      location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-get-access"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      SecRule REQUEST_URI socket.io/ "phase:1,id:12346,nolog,chain"
        SecRule REQUEST_BODY_LENGTH "@eq 0" "ctl:requestBodyAccess=off"
    # Add annotation to exclude 503 error pages from the list the cloud-platform error pages
    # and use our error pages for 503 errors
    nginx.ingress.kubernetes.io/custom-http-errors: "413,502,504"
spec:
  ingressClassName: "modsec"
  tls:
    - hosts:
       - "{{ .Values.host }}"
      {{- if .Values.secretName }}
      secretName: {{ .Values.secretName }}
      {{- end }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ .Values.service.port }}
          - path: "/socket.io/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-socket-server
                port:
                  number: {{ .Values.socketServer.service.port }}
{{- end }}
