{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cla-frontend.fullname" . -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cla-frontend.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- end }}
    {{- if .Values.ingress.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "cla-frontend.whitelist" . }}"
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippets: |
      location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }
spec:
  tls:
    - hosts:
       - "{{ .Values.host }}"
      {{- if .Values.secretName }}
      secretName: {{ .Values.secretName }}
      {{- end }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: "/"
          pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ .Values.service.port }}
          - path: "/socket.io/"
          pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-socket-server
                port:
                  number: {{ .Values.socketServer.service.port }}
{{- end }}
