apiVersion: v1
kind: Service
metadata:
  name: {{ include "cla-frontend.fullname" . }}-metrics
  labels:
    {{- include "cla-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9117
      name: metrics
      targetPort: 9117
  selector:
    {{- include "cla-metrics.selectorLabels" . | nindent 4 }}
