apiVersion: v1
kind: Service
metadata:
  name: {{ include "cla-frontend.fullname" . }}-socket-server
  labels:
    {{- include "cla-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.socketServer.service.type }}
  ports:
    - port: {{ .Values.socketServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cla-socket-server.selectorLabels" . | nindent 4 }}
