name: Build and Push image

on:
  workflow_call:
    inputs:
      ECR_REGION:
        required: true
        type: string

      ECR_REPOSITORY:
        required: true
        type: string

      ECR_REPOSITORY_SOCKET_SERVER:
        required: true
        type: string
        description: ECR repository (socket server)

    secrets:
      ECR_ROLE_TO_ASSUME:
        required: true

      ECR_REGISTRY_URL:
        required: true

      ECR_ROLE_TO_ASSUME_SOCKET_SERVER:
        required: true

    outputs:
      image_uri:
        description: "The docker image URI"
        value: ${{ jobs.build-and-push-to-ecr.outputs.image_uri }}

      image_tag:
        description: "The docker image tag"
        value: ${{ jobs.build-and-push-to-ecr.outputs.image_tag }}

jobs:
  build-and-push-to-ecr:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_uri: ${{ steps.meta.outputs.tags }}
      image_tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Generate image tag
        id: generate-tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAG="main-${GITHUB_SHA}"
          else
            TAG="branch-${GITHUB_SHA}"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Assume role in Cloud Platform
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.ECR_REGION }}

      - name: Login to container repository
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261fc3d4806db1fa66a15cc11113c456db8870a7
        with:
          mask-password: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}
          tags: |
            type=raw,value=${{ steps.generate-tag.outputs.tag }}

      - name: Debug image URL
        run: |
          echo "Built image:"
          echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up AWS credentials for socket server
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/ecr-auth@cb1ebcbca5efcd1e91b7ee1e27c73650c1bba9d8
        with:
          ecr_region: ${{ inputs.ECR_REGION }}
          ecr_role: ${{ secrets.ECR_ROLE_TO_ASSUME_SOCKET_SERVER }}
          role-session-name: laa-cla-frontend-socket-server

      - name: Build and push socket server image
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/build_and_push_with_cache@7c81d37978aef9418f7185d9ecf70e3cd1c63c02
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ inputs.ECR_REPOSITORY_SOCKET_SERVER }}
          dockerfile_path: cla_socketserver/Dockerfile
          image_tag: ${{ steps.generate-tag.outputs.tag }}